# Generated by Django 5.2.3 on 2025-07-13 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsarticle',
            name='views',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
