# Generated by Django 5.2.3 on 2025-07-13 01:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_update_like_comment_models'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='like',
            unique_together={('article', 'ip_address'), ('article', 'user')},
        ),
        migrations.AlterField(
            model_name='comment',
            name='anonymous_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='like',
            name='anonymous_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
