# Generated by Django 5.2.4 on 2025-07-24 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_fix_anonymous_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsarticle',
            name='featured_image',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='profile_picture',
        ),
    ]
